/*eslint-disable*/

export default [
    {
        index: 0,
        name: "分类1",
        desc: null,
        add_time: 1620990372,
        up_time: 1620990372,
        list: [
            {
                query_path: {
                    path: "/demo/get",
                    params: [],
                },
                edit_uid: 0,
                status: "done",
                type: "static",
                req_body_is_json_schema: true,
                res_body_is_json_schema: true,
                api_opened: false,
                index: 0,
                tag: ["tag1"],
                _id: 855247,
                method: "GET",
                catid: 217837,
                title: "get接口",
                path: "/demo/get",
                project_id: 58594,
                req_params: [],
                res_body_type: "json",
                desc: "<p>备注</p>\n",
                uid: 45392,
                add_time: 1620990390,
                up_time: 1620990480,
                req_query: [
                    {
                        required: "1",
                        _id: "609e5a107745840015c4e859",
                        name: "id",
                        example: "2",
                        desc: "222",
                    },
                    {
                        required: "1",
                        _id: "609e5a107745840015c4e858",
                        name: "name",
                        example: "333",
                        desc: "333",
                    },
                ],
                req_headers: [],
                req_body_form: [],
                __v: 0,
                markdown: "备注",
                res_body:
                    '{"$schema":"http://json-schema.org/draft-04/schema#","type":"object","properties":{"x":{"type":"number"},"y":{"type":"number"},"arr":{"type":"array","items":{"type":"number"}},"obj":{"type":"object","properties":{"foo":{"type":"number"}}}}}',
            },
            {
                query_path: {
                    path: "/demo/post",
                    params: [],
                },
                edit_uid: 0,
                status: "undone",
                type: "static",
                req_body_is_json_schema: true,
                res_body_is_json_schema: true,
                api_opened: false,
                index: 0,
                tag: ["tag1"],
                _id: 855250,
                method: "POST",
                catid: 217837,
                title: "post接口",
                path: "/demo/post",
                project_id: 58594,
                req_params: [],
                res_body_type: "json",
                desc: "",
                uid: 45392,
                add_time: 1620990504,
                up_time: 1620994797,
                req_query: [
                    {
                        required: "1",
                        _id: "609e6aed806fb50015dc765f",
                        name: "aa",
                        example: "22",
                        desc: "222",
                    },
                ],
                req_headers: [
                    {
                        required: "1",
                        _id: "609e6aed806fb50015dc7661",
                        name: "Content-Type",
                        value: "application/x-www-form-urlencoded",
                    },
                    {
                        required: "1",
                        _id: "609e6aed806fb50015dc7660",
                        name: "Accept",
                        value: "22",
                        example: "22",
                        desc: "22",
                    },
                ],
                req_body_form: [
                    {
                        required: "1",
                        _id: "609e6aed806fb50015dc7664",
                        name: "aa",
                        type: "text",
                        example: "11",
                    },
                    {
                        required: "1",
                        _id: "609e6aed806fb50015dc7663",
                        name: "bbb",
                        type: "text",
                        example: "22",
                        desc: "",
                    },
                    {
                        required: "1",
                        _id: "609e6aed806fb50015dc7662",
                        name: "ccc",
                        type: "text",
                        example: "333",
                        desc: "",
                    },
                ],
                __v: 0,
                req_body_other:
                    '{"$schema":"http://json-schema.org/draft-04/schema#","type":"object","properties":{"x":{"type":"number"},"y":{"type":"number"},"arr":{"type":"array","items":{"type":"number"}},"obj":{"type":"object","properties":{"foo":{"type":"number"}}}}}',
                markdown: "",
                res_body:
                    '{"$schema":"http://json-schema.org/draft-04/schema#","type":"object","properties":{}}',
                req_body_type: "form",
            },
        ],
    },
];
