
export default [{
  name: '新增文件夹',
  icon: '#iconxinzengwenjian',
  op: 'addRootFolder',
  shortcut: [],
  pin: true,
}, {
  name: '新增文件',
  icon: '#iconwenjian',
  op: 'addRootFile',
  shortcut: [],
  pin: true,
}, {
  name: '刷新banner',
  icon: '#iconshuaxin',
  op: 'freshBanner',
  shortcut: [],
  pin: true,
  viewOnly: true,
}, {
  name: '全局设置',
  icon: '#iconshezhi',
  op: 'config',
  shortcut: ['Ctrl', ','],
  pin: true,
}, {
  name: '回收站',
  icon: '#iconhuishouzhan',
  op: 'recycler',
  shortcut: ['Ctrl', 'Alt', 'R'],
  pin: true,
}, {
  name: '在线链接',
  icon: '#iconlink',
  op: 'generateLink',
  shortcut: ['Ctrl', 'L'],
  pin: false,
}, {
  name: '导出文档',
  icon: '#icondaochu1',
  op: 'exportDoc',
  shortcut: ['Ctrl', 'E'],
  pin: false,
}, {
  name: '导入文档',
  icon: '#icondaoru',
  op: 'importDoc',
  shortcut: ['Ctrl', 'I'],
  pin: false,
}, {
  name: '操作审计',
  icon: '#iconlishi',
  op: 'history',
  shortcut: ['Ctrl', 'H'],
  pin: false,
  viewOnly: true,
}, {
  name: '生成代码',
  icon: '#iconshengchengdaima',
  op: 'hook',
  shortcut: ['Ctrl', 'H'],
  pin: false,
  viewOnly: true,
}, {
  name: '接口编排',
  icon: '#iconbianpaixin',
  op: 'apiflow',
  shortcut: [],
  pin: false,
  viewOnly: true,
}];
